Mob Control
sh0ckR6/AchievementBorder pull request #3
Opened 2021-08-15 06:56 UTC by gtaEPIC

Have you ever experienced a mass number of hostile mobs spawning in such a small area?
Rhetorical question. The answer was yes.
The number of hostile mobs can be limited (and eventually will be configurable when you *cough cough* create the configuration thingy)

Currently:
If the border size is more than 16 blocks (wide or long) mobs can spawn at a limit of whatever the border size is.
For example, the Border size is 20 blocks, maximum of 20 hostile mobs.

<small>Side note, no I did not do the funny, though I might with a different version ;)</small>

2021-08-15 07:04 UTC, sh0ckR6 commented
Reviewing this when I get the chance, no guarantees it'll happen by the end of Sunday. Final touches need to be made for v1.0 release, so this will be released in a future (but soon) update (i.e. v1.1, v1.2).

2021-08-15 22:49 UTC, sh0ckR6 requested changes

2021-08-15 22:49 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +        return false;
This entire check can be replaced with an `instanceof`. All hostile mobs are part of the `Monster` class, which extends `Entity`. You're actually also missing spiders with the manual check, which while considered passive during the day, are hostile in caves/at night.

```suggestion
        return entity instanceof Monster
```

2021-08-15 22:49 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +        plugin.getLogger().log(Level.INFO, event.getEntity().getName() + " | " + isHostile(event.getEntity()));
Remove logs
```suggestion

```

2021-08-15 22:49 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +        }
Invert if (remove nesting if possible)
Also remove logging while we're here
```suggestion
        if (!isHostile(event.getEntity())) return;
        if (getMaxHostile() < hostileMobs + 1) event.getEntity().remove(); // Cancel spawn
        hostileMobs++;
```

2021-08-15 22:49 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +    private int hostileMobs = 0; // Number of hostile mobs that are spawned
Convert comment to JavaDoc
```suggestion
    /**
    * Number of hostile mobs that are spawned
    * 
    * @since 1.1
    */
    private int hostileMobs = 0;
```

2021-08-15 22:49 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +        }
Remove nesting & logging
```suggestion
        if (!isHostile(event.getEntity())) return;
        hostileMobs--;
```

2021-08-16 19:38 UTC, gtaEPIC commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +        return false;
I was originally just going with mobs that were marked hostile (according to another site) hence why there were some mobs missing. If this is the way you would want it then javadocs will need to be fixed for this as well. (I'll do that in a sec)

2021-08-16 19:46 UTC, sh0ckR6 requested changes
JavaDoc changes, other than that it's ready to merge

2021-08-16 19:46 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     * @param event Entity Removed Event
JavaDoc order
```
@param
@return
@throws
@author
@since
```

2021-08-16 19:46 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     * @param event New Entity Event
JavaDoc order
```
@param
@return
@throws
@author
@since
```

2021-08-16 19:46 UTC, sh0ckR6 commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     * @return True if hostile
JavaDoc order
```
@param
@return
@throws
@author
@since
```

2021-08-16 19:47 UTC, gtaEPIC reviewed
cool everything should be fixed now

2021-08-16 19:47 UTC, gtaEPIC commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     * @return True if hostile
```suggestion
    /**
     * Checks to see if an entity is a hostile mob
     *
     * @param entity The entity to check
     * @return True if hostile
     * @author gtaEPIC
     * @since 1.1
```
Fixing javadocs

2021-08-16 19:47 UTC, gtaEPIC commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     */
Fixing javadocs
```suggestion
    /**
     * Removes the number of hostile mobs (if it is hostile) that are alive
     *
     * @param event Entity Removed Event
     * @author gtaEPIC
     * @since 1.1
     */
```

2021-08-16 19:49 UTC, gtaEPIC commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     * @return True if hostile
t h a t s w h y I f I x e d i t :)

2021-08-16 19:50 UTC, gtaEPIC commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     * @param event New Entity Event
t h a t s w h y I f I x e d i t :)

2021-08-16 19:50 UTC, gtaEPIC commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +     * @param event Entity Removed Event
.

2021-08-16 19:51 UTC, sh0ckR6 approved these changes

2021-08-16 19:55 UTC, gtaEPIC commented on src/main/java/com/github/sh0ckr6/achievementborder/listeners/MobControl.java
> +        return entity instanceof Monster
```suggestion
        return entity instanceof Monster;
```
Somehow even I missed that e.e

2021-08-16 19:56 UTC, sh0ckR6 approved these changes

2021-08-16 20:00 UTC, sh0ckR6 requested changes

2021-08-16 20:01 UTC, sh0ckR6 approved these changes

2021-08-16 20:02 UTC, merged